version: "3.0"
services:
  stag-user-service:
    image: ${IMAGE_NAME}:${TAG}
    ports:
      - 7100:7100
      - 7101:7101
    environment:
      - GRPC_PORT=7100
      - HTTP_PORT=7101
      - DB_HOST=staging-postgre
      - DB_USERNAME=postgres
      - DB_PASSWORD=123456
      - DB_NAME=user-service
      - JWT_SECRET=secret
      - JWT_EXPIRED_TIME=6h
      - REDIS_SERVER=redis_staging:6379
      - GRPC_UTILITY_HOST=stag-utility-service:7300
    networks:
      - grpc_network
networks:
  grpc_network:
    external: true